name: GitHub Actions
on: push
jobs:
  action-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v5
      - name: Print index.html
        run: cat index.html
