name: Context variable demo
on: push
jobs:
  context-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Use context variables
        run: |
          echo "This workflow is triggered by ${{ github.actor }}"
          echo "The Repository name is ${{ github.repository }}"
      - name: Print all Variables under github context
        run: echo "${{ toJson(github) }}"

      - name: Print Environment Variables
        run: printenv
