name: Env Vars
on: workflow_dispatch
env:
  APP_ENV: "dev"
jobs:
  env_vars_demo:
    env:
      APP_ENV: "test"
    runs-on: ubuntu-latest
    steps:
      - name: Connecting to Environment
        run: echo "App is connecting to $APP_ENV"
