name: Hello World
on: push
jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Step
        run: |
          echo "Welcome to GitHub Actions"
          echo "Hello from ${{ vars.MY_NAME }}"
