name: If example with functions
on:
  push:
    branches:
      - main
      - develop
      - feature/**
jobs:
    quality_check:
        if: startsWith(github.ref_name, 'feature') && github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: Perform Code quality
              run: echo "Performing code quality check..."
    dev_deploy:
        if: github.ref_name == 'develop' && github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: Dev Deploy
              run: echo "Deploying the code to the development environment."
    prod_deploy:
        if: github.ref_name == 'main' && github.event_name == 'push'
        runs-on: ubuntu-latest
        steps:
            - name: Prod Deploy
              run: echo "Deploying the code to the production environment."
    success_notification:
        needs: ['quality_check', 'dev_deploy', 'prod_deploy']
        if: always() && !failure()
        runs-on: ubuntu-latest
        steps:
            - name: Success Notification
              run: echo "Deployment to production environment completed successfully."
    failure_notification:
        needs: ['quality_check', 'dev_deploy', 'prod_deploy']
        if: always() && failure()
        runs-on: ubuntu-latest
        steps:
            - name: Failure Notification
              run: echo "Deployment to production environment failed."
