name: Parameterized Deploy Workflow
on:
  workflow_dispatch: 
    inputs:
      environment:
        description: Choose the environment to deploy
        required: true
        default: development
        type: choice
        options:
          - development
          - staging
          - testing
          - production
      artifact_tag:
        description: Choose the Git Tag to Deploy
        required: true
jobs:
  input-parameter:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the App
        run: echo "Deploy the ${{ inputs.artifact_tag }} Application to ${{ inputs.environment }}"
