name: Or Condition
on: workflow_dispatch
jobs:
  or-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run for Rupa or RupaEnggVille
        if: github.actor == 'Rupa' || github.actor == 'RupaEnggVille'
        run: echo "It is triggered by Rupa or RupaEnggVille"
